apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dev
  namespace: mysql-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  longhorn-mysql-dev
  resources:
    requests:
      storage: 10Gi
