apiVersion: apps/v1
kind: Deployment
metadata:
  name: octaltask-web-front
  namespace: frontend-product
  labels:
    app: web-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: frontend-container
          image: ribun/taskmanagement_frontend_product:v3.0-20250622-163005
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_API_BASE
